M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date  8.07.2024 (пн) 15:30:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-08T15:30:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X49.2Y11.75
X49.2Y7.25
T2
X6.341Y15.215
X6.341Y3.785
T0
M30
